### ISSUE TITLE
cdr_selector = CDRResidueSelector() SmallKeyVector.hh line: 548

### ISSUE THREAD

**Issue by jiyanbio** [RosettaCommons/PyRosetta.notebooks#53]
>>> cdr_selector = CDRResidueSelector()

ERROR: Assertion `active( key )` failed.
ERROR:: Exit from: /home/benchmark/rosetta/source/build/PyRosetta/linux/clang-3.4.2/python-3.8/release/source/src/utility/keys/SmallKeyVector.hh line: 548
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: 

File: /home/benchmark/rosetta/source/build/PyRosetta/linux/clang-3.4.2/python-3.8/release/source/src/utility/keys/SmallKeyVector.hh:548
[ ERROR ] UtilityExitException
ERROR: Assertion `active( key )` failed.

**Comment by roccomoretti** [comment]
Is this from a notebook you ran as is, or from your own programming?

If the latter, my initial guess is that you forgot to call the init() function prior to calling other PyRosetta functions.

**Comment by jiyanbio** [comment]
sorry, I forgot run init().
