### ISSUE TITLE
I loaded the Python interpreter that deployed Pyrosetta Anaconda environment using PyCharm, but found many unresolved references while programming.

### ISSUE THREAD

**Issue by HGX-001** [RosettaCommons/PyRosetta.notebooks#67]
Hello everyone!
For the first time using Pyrosetta on a Linux server, I first created a new environment using anaconda. After entering this newly created environment, I used the conda install pyrosett command to successfully install pyrosetta, and then I successfully used pycharm's SSH interpreter locally. Loaded the python interpreter in this remote environment, but there were some problems when writing the program, for example, the reference “protocols” could not be found in the “__init__.py”, the unresolved reference “MinMover”, the unresolved reference 'ScoreFunction' and other such problems, of course, I also tried to start jupyter notebook in the terminal to write the program, this is no problem, but jupyter notebook is not convenient to debug the program, so I want to consult, have any friends encountered Same problem as me? Can share the solution.

**Comment by ajasja** [comment]
You have to make sure that PyCharmm is using the same environment (python version) as the jupyter notebook. It sounds like this is not the case.
