### ISSUE TITLE
Docking Protocols

### ISSUE THREAD

**Issue by LivC193** [RosettaCommons/PyRosetta.notebooks#77]
Dear Madam/Sir,

I am trying to understand the docking classes outlined [here](https://graylab.jhu.edu/PyRosetta.documentation/pyrosetta.rosetta.protocols.docking.html). 

How can I find out which classes use high resolution docking (full atomistic) and which use low resolution (centroid)? I am particularly interested in `DockMCMProtocol` and `DockingEnsemble`.

Furthermore I am interested in performing Flexible Docking using the `ensemble1` and `ensemble2` flags, is `DockingProtocol` able to do this? If so does it take care of the prepack step as well?

**Comment by jadolfbr** [comment]
Low and High res dock are covered in the docking chapter: https://nbviewer.org/github/RosettaCommons/PyRosetta.notebooks/blob/master/notebooks/07.02-Docking-Moves-in-Rosetta.ipynb
