### ISSUE TITLE
how to set "-nstruct" ,if I want to output 5 fastrelax model?

### ISSUE THREAD

**Issue by ak422** [RosettaCommons/PyRosetta.notebooks#80]
when I set the initial parameter as 
    init("-use_input_sc -ex1 -ex2 -nstruct 1 -out:path:pdb ./tutorial_output -out:path:score ./expected_output")
it output nothing, how can I get the pdb file result?

**Comment by ajasja** [comment]
I think you will get best results if you ask in slack in the pyrosetta 

In short since PyRosetta does not use the job distributor, the -nstruct flag might not have an effect. 
You can run the mover yourself N times and save the structure N times.

**Comment by ak422** [comment]
Thanks!
